name: Build

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  #   paths:
  #     - "source/**"
  #     - ".github/workflows/build.yml"

jobs:
  build:
    name: Export (Web)
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/bdrelling/godot:4.6-stable
      options: --user root

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Export (Web)
        run: |
          mkdir -p .builds/Web
          godot --headless --path source --export-release "Web" ../.builds/Web/index.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-web
          path: .builds/Web/
          retention-days: 14
